name: TaoVPS

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Nhập code'
        required: true
      pincode:
        description: 'Mã Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./caidat.ps1
    - name: Khởi động VPS
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./time.ps1
